# Generated by Django 2.0.2 on 2018-06-25 02:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('property_type', models.CharField(choices=[('sf', 'Single-Family Home'), ('mf', 'Muli-Family Home'), ('co', 'Condo, Townhouse or Apartment'), ('va', 'Vacation or Rental Property')], max_length=2)),
                ('rent_type', models.CharField(choices=[('no', 'No'), ('under_14', 'Yes, 14 days or less per year'), ('over_14', 'Yes, more than 14 days per year')], max_length=8)),
                ('primary_residence', models.BooleanField()),
                ('bedrooms', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(50)])),
                ('bathrooms', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('sqft', models.PositiveSmallIntegerField(verbose_name=[django.core.validators.MinValueValidator(1)])),
                ('year_bought', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)])),
                ('duration_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_forever', models.BooleanField(default=False)),
                ('home_value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999)])),
                ('mortgage_payment', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default=None, max_length=1)),
                ('referrer_name', models.CharField(blank=True, max_length=60)),
                ('credit_score', models.CharField(choices=[('excellent', 'Excellent (750+)'), ('good', 'Quite Good (700-749)'), ('fair', 'Alright (650-699)'), ('poor', 'Not Great (550-649)'), ('bad', 'In Trouble (300-549)'), ('i_dont_know', "I Don't Know")], max_length=15)),
                ('household_income_last_year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999)])),
                ('household_income_next_year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999)])),
                ('household_debt', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999)])),
                ('investment_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(1000000)])),
                ('use_case_debts', models.BooleanField(verbose_name='Needs help with debts')),
                ('use_case_diversify', models.BooleanField(verbose_name='Wants to diversify')),
                ('use_case_renovate', models.BooleanField(verbose_name='Wants to renovate')),
                ('use_case_education', models.BooleanField(verbose_name='Needs help paying for education')),
                ('use_case_buy_home', models.BooleanField(verbose_name='Wants to buy another home')),
                ('use_case_business', models.BooleanField(verbose_name='Wants to fund a buisness')),
                ('use_case_other', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Address')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry', to='custom_auth.Client')),
            ],
            options={
                'verbose_name_plural': 'inquiries',
            },
        ),
    ]
