# Generated by Django 2.0.2 on 2018-09-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_auto_20180719_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='when_interested',
            field=models.CharField(choices=[('asap', 'ASAP'), ('3_to_6_months', '3-6 Months'), ('7_to_12_months', '7-12 Months'), ('not_sure', 'Not sure yet - still learning')], default='not_sure', max_length=20),
        ),
    ]
