# Generated by Django 2.0.2 on 2018-09-17 15:38

from django.db import migrations, models


inquiries = []
def save_existing_duration_data(apps, schema_editor):
    """
    saves obsolete duration_years and duration_forever field values so they can be used to
    populate the new ten_year_duration_prediction field
    """
    Inquiry = apps.get_model('inquiry', 'Inquiry')
    if not Inquiry.objects.count():
        return
    for inquiry in Inquiry.objects.all():
        inquiries.append(
            {
                'id': inquiry.id,
                'duration_years': inquiry.duration_years,
                'duration_forever': inquiry.duration_forever,
            }
        )


def populate_ten_year_duration_prediction(apps, schema_editor):
    """
    use the saved obsolete duration_years and duration_forever field values to populate the
    new ten_year_duration_prediction field
    """
    if not inquiries:
        return
    Inquiry = apps.get_model('inquiry', 'Inquiry')
    for inquiry_data in inquiries:
        inquiry = Inquiry.objects.get(pk=inquiry_data['id'])
        if inquiry_data['duration_forever'] or inquiry_data['duration_years'] > 10:
            duration_prediction = 'over_10'
        else:
            duration_prediction = '10_or_less'
        inquiry.ten_year_duration_prediction = duration_prediction
        inquiry.full_clean()
        inquiry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_inquiry_when_interested'),
    ]

    operations = [
        migrations.RunPython(save_existing_duration_data),
        migrations.RemoveField(
            model_name='inquiry',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='credit_score',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='duration_forever',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='duration_years',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='household_income_last_year',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='household_income_next_year',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='mortgage_payment',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='sqft',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='year_bought',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='ten_year_duration_prediction',
            field=models.CharField(choices=[('over_10', 'Yes, more than 10 years'), ('10_or_less', 'No, 10 years or less'), ('dont_know', "Don't know")], default='10_or_less', max_length=10),
        ),
        migrations.RunPython(populate_ten_year_duration_prediction),
    ]
