# Generated by Django 2.0.2 on 2018-11-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0005_less_to_fewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='investment_size',
        ),
    ]
